drinks/urls.py
from django.urls import path 
from drinks.views import *
app_name='drinks'
urlpatterns=[
    path('blue_lagoon/',blue_lagoon,name='blue_lagoon'),
    path('orange_punch/',orange_punch,name='orange_punch'),
]

food/urls.py
from django.urls import path 
from food.views import *
app_name='food'
urlpatterns=[
    path('panipuri/',panipuri,name='panipuri'),
    path('kajukatli/',kajukatli,name='kajukatli'),
]

project2specic_url_nav/urls.py
from django.contrib import admin
from django.urls import path,include
import food,drinks

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('drinks/',include('drinks.urls')),
]

drinks/models.py
from django.db import models

# Create your models here.

food/models.py
from django.db import models

# Create your models here.

drinks/views.py
from django.shortcuts import render

# Create your views here.
def blue_lagoon(request):
    return  render(request,'blue_lagoon.html')

def orange_punch(request):
    return render(request,'orange_punch.html')

food/views.py
from django.shortcuts import render

# Create your views here.
def panipuri(request):
    return render(request,'panipuri.html')

def kajukatli(request):
    return render(request,'kajukatli.html')

templates/blue_lagoon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is blue_lagoon page</h1>
        <h1><a href="{% url 'food:panipuri' %}"<h2> navigate from blue_lagoon to panipuri</h2></a></h1>
        <h1><a href="{% url 'food:kajukatli' %}"<h2> navigate from blue_lagoon to kajukatli</h2></a></h1>
        <h1><a href="{% url 'drinks:orange_punch' %}"<h2> navigate from blue_lagoon to orange_punch</h2></a></h1>
    </center>

    
    
</body>
</html>

templates/kajukatli.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is kajukatli page</h1>
        <h1><a href="{% url 'food:panipuri' %}"<h2> navigate from kajukatli to panipuri</h2></a></h1>
        <h1><a href="{% url 'drinks:blue_lagoon' %}"<h2> navigate from kajukatli to blue_lagoon</h2></a></h1>
        <h1><a href="{% url 'drinks:orange_punch' %}"<h2> navigate from kajukatli to orange_punch</h2></a></h1>
    </center>

    
    
</body>
</html>

templates/orange_punch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is orange_punch page</h1>
        <h1><a href="{% url 'food:panipuri' %}"<h2> navigate from orange_punch to panipuri</h2></a></h1>
        <h1><a href="{% url 'food:kajukatli' %}"<h2> navigate from orange_punch to kajukatli</h2></a></h1>
        <h1><a href="{% url 'drinks:blue_lagoon' %}"<h2> navigate from orange_punch to blue_lagoon</h2></a></h1>
    </center>

    
    
</body>
</html>

templates/panipuri.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is panipuri page</h1>
        <h1><a href="{% url 'food:kajukatli' %}"<h2>navigate from panipuri to kajukatli</h2></a></h1>
        <h1><a href="{% url 'drinks:blue_lagoon' %}"<h2> navigate from panipuri to blue_lagoon</h2></a></h1>
        <h1><a href="{% url 'drinks:orange_punch' %}"<h2> navigate from panipuri to orange_punch</h2></a></h1>
    </center>

    
    
</body>
</html>